### ISSUE TITLE
rename the project?

### ISSUE THREAD

**Issue by delef** [73616c74/shield.cr#3]
Project name **Signal** conflicts with internal (core) enum and module (https://github.com/crystal-lang/crystal/blob/master/src/signal.cr). Is it possible to rename it to something else?

* SignalX
* SignalPassord
* maybe something completely different?

**Comment by 73616c74** [comment]
👍 The project name has been changed from "signal" to `shield.cr`
:)

**Comment by 73616c74** [comment]
Done.
