### ISSUE TITLE
More details on descriptions 

### ISSUE THREAD

**Issue by proyb6** [73616c74/shield.cr#4]
Descriptions need plenty of info, and are how good are those encrypted password against collisions?

What are the competitors or similar tools that’s is similar to shield.cr?

What is the decision to consider Crystal over C coding in this project?

Introduction yourself would be nice too.

**Comment by 73616c74** [comment]
> Descriptions need plenty of info, and are how good are those encrypted password against collisions?

Very safe, specific information: https://github.com/73616c74/shield.cr/blob/a860c585bcbc002fc496fae3c053c7b7fe96ede3/passwd.md 
But the readme needs some changes, so I temporarily deleted the introduction.

---

> What are the competitors or similar tools that’s is similar to shield.cr?

I am not quite sure, maybe it is 1Password／National Security Agency? :-)

---

> What is the decision to consider Crystal over C coding in this project?

I think there may be in the future.

---

> Introduction yourself would be nice too.

Yes, I need some time to perfect (introduce) this project.
Also, I am making a password vault for shield.cr (vault.cr).

**Comment by proyb6** [comment]
I notice the lighthouse logo and product name "shield" don't match, in my opinion, you need a more sophisticated branding logo and screenshots to present a modern and differentiate from existing products that privacy-conscious users will feel more comfortable to use. At this point is the best time to consider for improvement?

**Comment by 73616c74** [comment]
Good question, the logo issue is resolved in [dd8bcc](https://github.com/73616c74/shield.cr/commit/41a16ec572241cf87d93f943470ea32f8513a9c7) commit.
Password generation workflow issue was resolved in [dd8bcff](https://github.com/73616c74/shield.cr/commit/dd8bcff45b3e00a23bb54eaec5a01fd3d1cf691a) commit.

**Comment by 73616c74** [comment]
If there are any problems, please let me know and I will solve them. :)
