### ISSUE TITLE
OpenSSL::Digest::UnsupportedError

### ISSUE THREAD

**Issue by webmastak** [73616c74/shield.cr#5]
Crystal 0.27.2 (2019-02-05)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu

Made:
1) `git clone https://github.com/73616c74/shield.cr.git`
2) `shards install`
3) `crystal build --release src/shield.cr`

After entering TitleName gives an error:
[![https://i.imgur.com/FRm3WLz.png](https://i.imgur.com/FRm3WLz.png)](https://i.imgur.com/FRm3WLz.png)

The binary file from **Shield_Linux.tar.gz** works as it should.
But it's strange that your file weighs 3.9mb my 718kb

I tried to do static linking via: 
`docker run --rm -it -v $PWD:/app -w /app jrei/crystal-alpine crystal build --static --release --no-debug src/shield.cr` 
The file weighs 14mb and I get the same error.

Did you compile the release file that is here **Shield_Linux.tar.gz** under ubuntu via Docker? If so please share the repository.
[![https://i.imgur.com/dgOCJwq.png](https://i.imgur.com/dgOCJwq.png)](https://i.imgur.com/dgOCJwq.png)

**Comment by 73616c74** [comment]
Sounds like your openssl is incorrectly installed. Try this:
```bash
$ irb
>> require 'openssl'
=> true
>> OpenSSL::Digest.new('dsaEncryption')
=> #<OpenSSL::Digest: da39a3ee5e6b4b0d3255bfef95601890afd80709>
>> OpenSSL::OPENSSL_VERSION_NUMBER.to_s(16)
=> "9081df"
```
```bash
$icr
icr(0.27.2) > require "openssl"
 => ok
icr(0.27.2) > OpenSSL::Digest.new("dsaEncryption")
 => #<OpenSSL::Digest:0x10fd90f20 @name="dsaEncryption", @ctx=Pointer(LibCrypto::EVP_MD_CTX_Struct)@0x7faafad00fe0>
```
This stackoverflow may be helpful [http://stackoverflow.com/questions/15907103/ruby-not-finding-new-version-of-openssl-not-setting-opensslopen-ssl-version-a](http://stackoverflow.com/questions/15907103/ruby-not-finding-new-version-of-openssl-not-setting-opensslopen-ssl-version-a)

**Comment by 73616c74** [comment]
The release is currently created [automatically](https://github.com/73616c74/shield.cr/blob/master/bin/ci) by [Travis-CI](https://travis-ci.org/73616c74/shield.cr/builds).
Will add docker support in the future.

**Comment by webmastak** [comment]
[![https://i.imgur.com/g853aPO.png](https://i.imgur.com/g853aPO.png)](https://i.imgur.com/g853aPO.png)

**Comment by 73616c74** [comment]
Hi webmastak, Have you tried updating the OpenSSL package on the Ubuntu machine? And maybe upgrade could correct the issue.
Please try `sudo apt-get install openssl-dev`

**Comment by webmastak** [comment]
I do not have Ubuntu. I have a  [manjaro](https://manjaro.org/) and i don't have openssl-dev

**Comment by 73616c74** [comment]
Sorry, reply some late, Please test this Dockerfile.
I have some problems with my network and can't download (stuck😥), so you can test it. 
```dockerfile
FROM ubuntu:latest
FROM crystallang/crystal:0.27.2

RUN git clone --depth=50 --branch=v0.2.0 https://github.com/73616c74/shield.cr.git 73616c74/shield.cr
RUN cd 73616c74/shield.cr
RUN git checkout -qf v0.2.0

RUN export DEPLOY_FILENAME=Shield_Linux.tar.gz
RUN export DEPLOY_DIR=bin/linux
RUN export DEPLOY_STATIC="--static"

RUN crystal --version
RUN shards --version

RUN chmod +x bin/ci
RUN bin/ci prepare_build
RUN bin/ci build
RUN bin/ci deploy
```

**Comment by webmastak** [comment]
[![https://i.imgur.com/EDq8vwo.png](https://i.imgur.com/EDq8vwo.png)](https://i.imgur.com/EDq8vwo.png)
[![https://i.imgur.com/39N9XJ4.png](https://i.imgur.com/39N9XJ4.png)](https://i.imgur.com/39N9XJ4.png)
[![https://i.imgur.com/Ze1emny.png](https://i.imgur.com/Ze1emny.png)](https://i.imgur.com/Ze1emny.png)

**Comment by 73616c74** [comment]
So, is the problem solved🤔?

**Comment by webmastak** [comment]
[![https://i.imgur.com/J4Pwraj.png](https://i.imgur.com/J4Pwraj.png)](https://i.imgur.com/J4Pwraj.png)
[![https://i.imgur.com/2GzT7It.png](https://i.imgur.com/2GzT7It.png)](https://i.imgur.com/2GzT7It.png)
[![https://i.imgur.com/TZc3SCJ.png](https://i.imgur.com/TZc3SCJ.png)](https://i.imgur.com/TZc3SCJ.png)
[![https://i.imgur.com/9tt60Rd.png](https://i.imgur.com/9tt60Rd.png)](https://i.imgur.com/9tt60Rd.png)

**Comment by 73616c74** [comment]
@webmastak 👍 Okay, I think it should have been solved.  :)

**Comment by 73616c74** [comment]
I am testing a vault([Vault.cr](https://github.com/73616c74/vault.cr)) based on Shield.cr
But Not yet completed, it will take some time.
If you still have problem, you can continue to reply, 
if you have already solved, 
please click the resolved button (Close) :)

**Comment by webmastak** [comment]
Thanks for the help.

**Comment by webmastak** [comment]
What a pity that you deleted the **Vault.cr** repository. I wanted to test
